# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'COApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for COApp
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'



  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'COAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'COApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for COApp-tvOS

  target 'COApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
